openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/clients/:
    get:
      operationId: clients_list
      tags:
      - clients
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Client'
          description: ''
    post:
      operationId: clients_create
      tags:
      - clients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
  /api/clients/{id}/:
    get:
      operationId: clients_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this client.
        required: true
      tags:
      - clients
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
    put:
      operationId: clients_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this client.
        required: true
      tags:
      - clients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Client'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Client'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Client'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
    patch:
      operationId: clients_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this client.
        required: true
      tags:
      - clients
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedClient'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedClient'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedClient'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
          description: ''
    delete:
      operationId: clients_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this client.
        required: true
      tags:
      - clients
      responses:
        '204':
          description: No response body
  /api/register/:
    post:
      operationId: register_create
      tags:
      - register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Register'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Register'
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Register'
          description: ''
  /api/todoItems/:
    get:
      operationId: todoItems_list
      tags:
      - todoItems
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoItem'
          description: ''
    post:
      operationId: todoItems_create
      tags:
      - todoItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TodoItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TodoItem'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
          description: ''
  /api/todoItems/{id}/:
    get:
      operationId: todoItems_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo item.
        required: true
      tags:
      - todoItems
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
          description: ''
    put:
      operationId: todoItems_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo item.
        required: true
      tags:
      - todoItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TodoItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TodoItem'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
          description: ''
    patch:
      operationId: todoItems_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo item.
        required: true
      tags:
      - todoItems
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTodoItem'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTodoItem'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTodoItem'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
          description: ''
    delete:
      operationId: todoItems_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo item.
        required: true
      tags:
      - todoItems
      responses:
        '204':
          description: No response body
  /api/todoLists/:
    get:
      operationId: todoLists_list
      tags:
      - todoLists
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoList'
          description: ''
    post:
      operationId: todoLists_create
      tags:
      - todoLists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TodoList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
  /api/todoLists/{id}/:
    get:
      operationId: todoLists_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
    put:
      operationId: todoLists_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TodoList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TodoList'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
    patch:
      operationId: todoLists_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
    delete:
      operationId: todoLists_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      responses:
        '204':
          description: No response body
  /api/todoLists/{id}/assign/:
    patch:
      operationId: todoLists_assign_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedTodoList'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
  /api/todoLists/{id}/items/:
    get:
      operationId: todoLists_items_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this todo list.
        required: true
      tags:
      - todoLists
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoList'
          description: ''
  /api/users/:
    get:
      operationId: users_list
      tags:
      - users
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/:
    get:
      operationId: users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - users
      security:
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/assigned_items/:
    get:
      operationId: users_assigned_items_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/assigned_lists/:
    get:
      operationId: users_assigned_lists_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this user.
        required: true
      tags:
      - users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        avatar:
          type: string
          format: uri
          nullable: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        project_name:
          type: string
          maxLength: 150
        project_revenue:
          type: string
          format: decimal
          pattern: ^-?\d{0,9}(?:\.\d{0,3})?$
        invited_by:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - email
      - id
      - updated_at
    PatchedClient:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        avatar:
          type: string
          format: uri
          nullable: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        project_name:
          type: string
          maxLength: 150
        project_revenue:
          type: string
          format: decimal
          pattern: ^-?\d{0,9}(?:\.\d{0,3})?$
        invited_by:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
    PatchedTodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        list_within:
          type: string
          format: uuid
    PatchedTodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        owned_by:
          type: string
          format: uuid
        assigned_to:
          type: string
          format: uuid
          readOnly: true
          nullable: true
    Register:
      type: object
      properties:
        avatar:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          maxLength: 150
        role:
          $ref: '#/components/schemas/RoleEnum'
    RoleEnum:
      enum:
      - standard
      - admin
      type: string
      description: |-
        * `standard` - Standard
        * `admin` - Admin
    StatusEnum:
      enum:
      - negotiating
      - won
      - lost
      type: string
      description: |-
        * `negotiating` - Negotiating
        * `won` - Won
        * `lost` - Lost
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        content:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        list_within:
          type: string
          format: uuid
      required:
      - created_at
      - id
      - list_within
      - updated_at
    TodoList:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          maxLength: 150
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        owned_by:
          type: string
          format: uuid
        assigned_to:
          type: string
          format: uuid
          readOnly: true
          nullable: true
      required:
      - assigned_to
      - created_at
      - id
      - owned_by
      - updated_at
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 254
        avatar:
          type: string
          format: uri
          nullable: true
        name:
          type: string
          maxLength: 150
        role:
          $ref: '#/components/schemas/RoleEnum'
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - created_at
      - email
      - id
      - updated_at
